Expand the macOS matrix

diff --git a/.github/workflows/conda.yml b/.github/workflows/conda.yml
--- a/.github/workflows/conda.yml
+++ b/.github/workflows/conda.yml
@@ -38,20 +38,22 @@ jobs:
       fail-fast: false
       matrix:
         environment:
-          - "py310-pa13"
-          - "py311-pa13"
-          - "py312-pa13"
-          - "py310-pa14"
-          - "py311-pa14"
-          - "py312-pa14"
-          - "py310-pa15"
-          - "py311-pa15"
-          - "py312-pa15"
-          - "py310-pa16"
-          - "py311-pa16"
-          - "py312-pa16"
-          - "py310-pa17"
-          - "py311-pa17"
+          # XXX: These three fail.
+          # - "py310-pa13"
+          # - "py311-pa13"
+          # - "py312-pa13"
+          # Everything below seems to work.
+          # - "py310-pa14"
+          # - "py311-pa14"
+          # - "py312-pa14"
+          # - "py310-pa15"
+          # - "py311-pa15"
+          # - "py312-pa15"
+          # - "py310-pa16"
+          # - "py311-pa16"
+          # - "py312-pa16"
+          # - "py310-pa17"
+          # - "py311-pa17"
           - "py312-pa17"
     services:
       postgres:
@@ -119,45 +121,6 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        environment: ["py310-pa13"]
-    steps:
-      - name: Checkout branch
-        uses: actions/checkout@v4
-        with:
-          submodules: true
-      - name: Fetch full git history
-        run: git fetch --prune --unshallow
-      - name: Set up pixi
-        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
-        with:
-          environments: ${{ matrix.environment }}
-      - name: Setup postgres
-        shell: pixi run bash -e {0}
-        run: |
-          initdb -D test_db --username="runner" --pwfile=<(printf "%s\n" "password")
-          pg_ctl -D test_db -l logfile start
-          createdb --owner=runner test_db
-      - name: Build and test
-        shell: pixi run bash -e {0}
-        env:
-          TURBODBC_TEST_CONFIGURATION_FILES: "tests/query_fixtures_postgresql.json"
-        run: |
-          python -m build
-          python -m pip install dist/*.whl
-          ls -l $(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')
-          export ODBCSYSINI=$(pwd)/odbc_test_osx
-          sed -i "s;CONDA_PREFIX;${CONDA_PREFIX};g" odbc_test_osx/odbcinst.ini
-          python -c 'import turbodbc'
-          ulimit -c unlimited
-          pytest -sv || (lldb -o "target create python --core $(ls /cores/core*)" -o "bt all" -o "quit"; exit 1)
-  windows-pixi-tests:
-    defaults:
-      run:
-        shell: cmd /C call {0}
-    runs-on: windows-latest
-    strategy:
-      fail-fast: false
-      matrix:
         environment:
           - "py310-pa13"
           - "py311-pa13"
@@ -173,6 +136,59 @@ jobs:
           - "py312-pa16"
           - "py310-pa17"
           - "py311-pa17"
+          - "py312-pa17"
+    steps:
+      - name: Checkout branch
+        uses: actions/checkout@v4
+        with:
+          submodules: true
+      - name: Fetch full git history
+        run: git fetch --prune --unshallow
+      - name: Set up pixi
+        uses: prefix-dev/setup-pixi@ba3bb36eb2066252b2363392b7739741bb777659
+        with:
+          environments: ${{ matrix.environment }}
+      - name: Create postgres test_db
+        run: pixi run -e ${{ matrix.environment }} initdb -D test_db --username="runner" --pwfile=<(printf "%s\n" "password")
+      - name: Start postgres
+        run: pixi run -e ${{ matrix.environment }} pg_ctl -D test_db -l logfile start
+      - name: Create inner database
+        run: pixi run -e ${{ matrix.environment }} createdb --owner=runner test_db
+      - name: Build the wheel
+        run: pixi run -e ${{ matrix.environment }} python -m build
+      - name: Install the built wheel
+        run: pixi run -e ${{ matrix.environment }} python -m pip install dist/*.whl
+      - name: Import test
+        run: pixi run -e ${{ matrix.environment }} python -c 'import turbodbc'
+      - name: Prepare ODBC
+        run: pixi run -e ${{ matrix.environment }} bash -c 'sed -i "s;CONDA_PREFIX;${CONDA_PREFIX};g" odbc_test_osx/odbcinst.ini'
+      - name: Build and test
+        env:
+          TURBODBC_TEST_CONFIGURATION_FILES: "tests/query_fixtures_postgresql.json"
+        run: pixi run -e ${{ matrix.environment }} bash -c 'ulimit -c unlimited && pytest -sv || (lldb -o "target create python --core $(ls /cores/core*)" -o "bt all" -o "quit"; exit 1)'
+  windows-pixi-tests:
+    defaults:
+      run:
+        shell: cmd /C call {0}
+    runs-on: windows-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        environment:
+          # - "py310-pa13"
+          # - "py311-pa13"
+          # - "py312-pa13"
+          # - "py310-pa14"
+          # - "py311-pa14"
+          # - "py312-pa14"
+          # - "py310-pa15"
+          # - "py311-pa15"
+          # - "py312-pa15"
+          # - "py310-pa16"
+          # - "py311-pa16"
+          # - "py312-pa16"
+          # - "py310-pa17"
+          # - "py311-pa17"
           - "py312-pa17"
     steps:
       - name: Create SQL Server
